/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chaidir.App;

import Chaidir.Dao.AsuransiDAO;
import Chaidir.Model.Tarif;
import Chaidir.Dao.TarifFileDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class WindowApp extends javax.swing.JFrame {
   
    List<Tarif> kotaTujuan;
    Tarif[] kota;
    Tarif tarif = new Tarif();
    
    public WindowApp() {
       initpaket();
       tarif = new Tarif();
       getKota();
       initComponents();
    }
    
    public void initpaket(){
        try {
            kotaTujuan = TarifFileDAO.PaketKota();
        } catch (Exception e) {
        }
    }
    
    public Tarif[] getKota() {
        int size = kotaTujuan.size();
        kota = new Tarif[size];
        
        for (int i = 0; i < size; i++) {
            Tarif tarif = kotaTujuan.get(i);
            kota[i] = tarif;
        }
        
        return kota;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayananBTNGRP = new javax.swing.ButtonGroup();
        AsuransiBTNGRP = new javax.swing.ButtonGroup();
        JenisBayarBTNGRP = new javax.swing.ButtonGroup();
        dialogPane = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        namaDialog = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        nama2Dialog = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tujuanDialog = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tarifDialog = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jenisDialog = new javax.swing.JTextField();
        doneDialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaPengirimTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatPengirimTF = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        telpTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kotaPengirimCombo = new javax.swing.JComboBox<>(kota);
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaPenerimaTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatPenerimaTF = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        telpPenerimaTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kotaPenerimaCombo = new javax.swing.JComboBox<>(kota);
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kotaDPPaket = new javax.swing.JComboBox<>(kota);
        jLabel14 = new javax.swing.JLabel();
        jenisBarangCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        noPaketTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        yaRadio = new javax.swing.JRadioButton();
        tidakRadio = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        cashRadio = new javax.swing.JRadioButton();
        debitRadio = new javax.swing.JRadioButton();
        hargaBarangTF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ccRadio = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ketAsuransi = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        beratTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panjangTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lebarTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tinggiTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sdsRadio = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        onsRadio = new javax.swing.JRadioButton();
        regulerRadio = new javax.swing.JRadioButton();
        kilatRadio = new javax.swing.JRadioButton();
        hsRadio = new javax.swing.JRadioButton();
        hitungBTN = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        dialogPane.setMinimumSize(new java.awt.Dimension(500, 350));

        jLabel32.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel32.setText("Data Transaksi");

        jLabel33.setText("Nama Pengirim :");

        namaDialog.setEditable(false);

        jLabel34.setText("Nama Penerima :");

        nama2Dialog.setEditable(false);

        jLabel35.setText("Kota Tujuan :");

        tujuanDialog.setEditable(false);

        jLabel36.setText("Tarif Akhir :");

        tarifDialog.setEditable(false);

        jLabel31.setText("Jenis Pengiriman :");

        jenisDialog.setEditable(false);
        jenisDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisDialogActionPerformed(evt);
            }
        });

        doneDialog.setText("Done");
        doneDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogPaneLayout = new javax.swing.GroupLayout(dialogPane.getContentPane());
        dialogPane.getContentPane().setLayout(dialogPaneLayout);
        dialogPaneLayout.setHorizontalGroup(
            dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPaneLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 31, Short.MAX_VALUE)
                        .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(namaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPaneLayout.createSequentialGroup()
                        .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34)
                            .addComponent(jLabel36)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tarifDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(nama2Dialog)
                            .addComponent(tujuanDialog)
                            .addComponent(jenisDialog, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(dialogPaneLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(doneDialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogPaneLayout.setVerticalGroup(
            dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama2Dialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuanDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarifDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addComponent(doneDialog)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Aplikasi Pengiriman Paket Khaleem");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Data Pengirim :");

        jLabel3.setText("Nama :");

        namaPengirimTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPengirimTFActionPerformed(evt);
            }
        });

        jLabel4.setText("Alamat :");

        alamatPengirimTF.setColumns(20);
        alamatPengirimTF.setRows(5);
        alamatPengirimTF.setText("\n");
        jScrollPane1.setViewportView(alamatPengirimTF);

        jLabel5.setText("No Telepon :");

        telpTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpTFActionPerformed(evt);
            }
        });

        jLabel11.setText("Kota :");

        kotaPengirimCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaPengirimComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kotaPengirimCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(telpTF)
                            .addComponent(namaPengirimTF))
                        .addGap(5, 5, 5))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(namaPengirimTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(kotaPengirimCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Data Penerima :");

        jLabel7.setText("Nama :");

        jLabel8.setText("Alamat :");

        alamatPenerimaTF.setColumns(20);
        alamatPenerimaTF.setRows(5);
        jScrollPane2.setViewportView(alamatPenerimaTF);

        jLabel9.setText("No Telepon :");

        jLabel10.setText("Kota :");

        kotaPenerimaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaPenerimaComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telpPenerimaTF)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(namaPenerimaTF)
                            .addComponent(kotaPenerimaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(namaPenerimaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(kotaPenerimaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telpPenerimaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Data Paket :");

        jLabel13.setText("No Paket :");

        kotaDPPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaDPPaketActionPerformed(evt);
            }
        });

        jLabel14.setText("Kota Tujuan :");

        jenisBarangCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokumen", "Elektronik", "Makanan", "Pakaian" }));

        jLabel15.setText("Jenis Barang :");

        noPaketTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPaketTFActionPerformed(evt);
            }
        });

        jLabel16.setText("Tanggal Kirim :");

        jLabel27.setText("Asuransi :");

        AsuransiBTNGRP.add(yaRadio);
        yaRadio.setText("Ya");
        yaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaRadioActionPerformed(evt);
            }
        });

        AsuransiBTNGRP.add(tidakRadio);
        tidakRadio.setText("Tidak");
        tidakRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakRadioActionPerformed(evt);
            }
        });

        jLabel28.setText("Jenis Pembayaran :");

        JenisBayarBTNGRP.add(cashRadio);
        cashRadio.setText("Cash");

        JenisBayarBTNGRP.add(debitRadio);
        debitRadio.setText("Debit");

        hargaBarangTF.setEnabled(false);
        hargaBarangTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBarangTFActionPerformed(evt);
            }
        });

        jLabel29.setText("Harga Barang :");
        jLabel29.setEnabled(false);

        ccRadio.setText("Credit Card");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kotaDPPaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jenisBarangCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noPaketTF)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(yaRadio)
                                .addGap(18, 18, 18)
                                .addComponent(tidakRadio)
                                .addGap(18, 18, 18)
                                .addComponent(ketAsuransi)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(hargaBarangTF))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cashRadio)
                                .addGap(18, 18, 18)
                                .addComponent(debitRadio)
                                .addGap(18, 18, 18)
                                .addComponent(ccRadio)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(noPaketTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaDPPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisBarangCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yaRadio)
                                .addComponent(tidakRadio)
                                .addComponent(ketAsuransi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaBarangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(cashRadio)
                            .addComponent(debitRadio)
                            .addComponent(ccRadio)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        beratTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratTFActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel18.setText("CM");

        jLabel19.setText("Panjang :");

        panjangTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangTFActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel20.setText("CM");

        jLabel21.setText("Lebar :");

        lebarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarTFActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel22.setText("KG");

        jLabel23.setText("Tinggi :");

        tinggiTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiTFActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel24.setText("CM");

        jLabel25.setText("Dimensi :");

        jLabel17.setText("Berat :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(beratTF)
                            .addComponent(panjangTF)
                            .addComponent(lebarTF)
                            .addComponent(tinggiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(beratTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(panjangTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lebarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tinggiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LayananBTNGRP.add(sdsRadio);
        sdsRadio.setText("Same Day Service");
        sdsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdsRadioActionPerformed(evt);
            }
        });

        jLabel26.setText("Jenis Layanan :");

        LayananBTNGRP.add(onsRadio);
        onsRadio.setText("One Night Service");

        LayananBTNGRP.add(regulerRadio);
        regulerRadio.setText("Reguler");

        LayananBTNGRP.add(kilatRadio);
        kilatRadio.setText("Kilat");

        LayananBTNGRP.add(hsRadio);
        hsRadio.setText("Holiday Service");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onsRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(sdsRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kilatRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regulerRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hsRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(20, 20, 20)
                .addComponent(regulerRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kilatRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sdsRadio)
                .addGap(9, 9, 9)
                .addComponent(onsRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hsRadio)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        hitungBTN.setText("Submit");
        hitungBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBTNActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Master Data");

        jMenuItem1.setText("Data Tarif");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hitungBTN)
                                .addGap(137, 137, 137)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(hitungBTN))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telpTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpTFActionPerformed

    private void namaPengirimTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPengirimTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPengirimTFActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void noPaketTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPaketTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noPaketTFActionPerformed

    private void beratTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratTFActionPerformed

    private void panjangTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangTFActionPerformed

    private void lebarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarTFActionPerformed

    private void tinggiTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiTFActionPerformed

    private void sdsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdsRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdsRadioActionPerformed

    private void kotaPengirimComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaPengirimComboActionPerformed
        // TODO add your handling code here:
        Tarif tarif = (Tarif)kotaPengirimCombo.getSelectedItem();
    }//GEN-LAST:event_kotaPengirimComboActionPerformed

    private void kotaPenerimaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaPenerimaComboActionPerformed
        // TODO add your handling code here:
        Tarif tarif = (Tarif)kotaPenerimaCombo.getSelectedItem();
    }//GEN-LAST:event_kotaPenerimaComboActionPerformed

    private void kotaDPPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaDPPaketActionPerformed
        // TODO add your handling code here:
        Tarif tarif = (Tarif)kotaDPPaket.getSelectedItem();
        
    }//GEN-LAST:event_kotaDPPaketActionPerformed

    private void hargaBarangTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBarangTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBarangTFActionPerformed

    private void yaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaRadioActionPerformed
        // TODO add your handling code here:
        hargaBarangTF.setEnabled(true);
        hargaBarangTF.setEditable(true);
        jLabel29.setEnabled(true);
    }//GEN-LAST:event_yaRadioActionPerformed

    private void tidakRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakRadioActionPerformed
        // TODO add your handling code here:
        hargaBarangTF.setEnabled(false);
        hargaBarangTF.setEditable(false);
        jLabel29.setEnabled(false);
    }//GEN-LAST:event_tidakRadioActionPerformed

    private void hitungBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBTNActionPerformed
        
        try {
        
        if (yaRadio.isSelected()) {
            
        AsuransiDAO pa = new AsuransiDAO();
        String namaKota = String.valueOf(kotaDPPaket.getSelectedItem());
        String beraTot = beratTF.getText();
        int berat = Integer.parseInt(beraTot);
        String harga = hargaBarangTF.getText();
        double hargaBarang = Double.parseDouble(harga);
        tarif = pa.hitungHarga(namaKota, berat, hargaBarang);

        } else {    
              
        AsuransiDAO p = new AsuransiDAO();
        String namaKota = String.valueOf(kotaDPPaket.getSelectedItem());
        String beraTot = beratTF.getText();
        int berat = Integer.parseInt(beraTot);
        
        tarif = p.hitungHarga(namaKota, berat);
                
        }
        
        if(regulerRadio.isSelected()){
            tarifDialog.setText(tarif.getReguler()+"");
        }
        
        if(kilatRadio.isSelected()){
            tarifDialog.setText(tarif.getKilat()+"");
        }
        
        if(sdsRadio.isSelected()){
            tarifDialog.setText(tarif.getSds()+"");
        }
        
        if(onsRadio.isSelected()){
            tarifDialog.setText(tarif.getOns()+"");
        }
        
        if(hsRadio.isSelected()){
            tarifDialog.setText(tarif.getHds()+"");
        }

       dialogPane.dispose();
       dialogPane.setVisible(true);
       
       namaDialog.setText(namaPengirimTF.getText());
       nama2Dialog.setText(namaPenerimaTF.getText());
       tujuanDialog.setText(""+kotaDPPaket.getSelectedItem());
       String jenis = "";
       if(LayananBTNGRP.isSelected(regulerRadio.getModel())){
       jenis = regulerRadio.getActionCommand();
       }
       if(LayananBTNGRP.isSelected(kilatRadio.getModel())){
       jenis = kilatRadio.getActionCommand();
       }
       if(LayananBTNGRP.isSelected(onsRadio.getModel())){
       jenis = onsRadio.getActionCommand();
       }
       if(LayananBTNGRP.isSelected(sdsRadio.getModel())){
       jenis = sdsRadio.getActionCommand();
       }
       if(LayananBTNGRP.isSelected(hsRadio.getModel())){
       jenis = hsRadio.getActionCommand();
       }
       jenisDialog.setText(jenis);
       tarifDialog.setText(tarifDialog.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "DATA HARUS DIISI!");
        }
        
    }//GEN-LAST:event_hitungBTNActionPerformed

    private void jenisDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisDialogActionPerformed

    private void doneDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneDialogActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_doneDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AsuransiBTNGRP;
    private javax.swing.ButtonGroup JenisBayarBTNGRP;
    private javax.swing.ButtonGroup LayananBTNGRP;
    private javax.swing.JTextArea alamatPenerimaTF;
    private javax.swing.JTextArea alamatPengirimTF;
    private javax.swing.JTextField beratTF;
    private javax.swing.JRadioButton cashRadio;
    private javax.swing.JRadioButton ccRadio;
    private javax.swing.JRadioButton debitRadio;
    private javax.swing.JDialog dialogPane;
    private javax.swing.JButton doneDialog;
    private javax.swing.JTextField hargaBarangTF;
    private javax.swing.JButton hitungBTN;
    private javax.swing.JRadioButton hsRadio;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisBarangCombo;
    private javax.swing.JTextField jenisDialog;
    private javax.swing.JLabel ketAsuransi;
    private javax.swing.JRadioButton kilatRadio;
    private javax.swing.JComboBox<Tarif> kotaDPPaket;
    private javax.swing.JComboBox<Tarif> kotaPenerimaCombo;
    private javax.swing.JComboBox<Tarif> kotaPengirimCombo;
    private javax.swing.JTextField lebarTF;
    private javax.swing.JTextField nama2Dialog;
    private javax.swing.JTextField namaDialog;
    private javax.swing.JTextField namaPenerimaTF;
    private javax.swing.JTextField namaPengirimTF;
    private javax.swing.JTextField noPaketTF;
    private javax.swing.JRadioButton onsRadio;
    private javax.swing.JTextField panjangTF;
    private javax.swing.JRadioButton regulerRadio;
    private javax.swing.JRadioButton sdsRadio;
    private javax.swing.JTextField tarifDialog;
    private javax.swing.JTextField telpPenerimaTF;
    private javax.swing.JTextField telpTF;
    private javax.swing.JRadioButton tidakRadio;
    private javax.swing.JTextField tinggiTF;
    private javax.swing.JTextField tujuanDialog;
    private javax.swing.JRadioButton yaRadio;
    // End of variables declaration//GEN-END:variables
}
